# Generated by Django 3.0.7 on 2022-08-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='complexity',
            field=models.CharField(choices=[('Master', 'master'), ('Middle', 'middle'), ('Beginner', 'beginner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plants',
            name='lighting',
            field=models.CharField(choices=[('Sunny', 'sunny'), ('Half-shade', 'half-shade'), ('Dark', 'dark')], max_length=20),
        ),
    ]
